variables:
  GIT_DEPTH: 1

image:
  name: registry.gitlab.com/gitlab-org/terraform-images/releases/1.0:latest

verify:
  stage: test
  script:
  - for i in $(find . -name ".?*" -prune -o -type d -print); do terraform fmt -check -diff $i; done
  - for i in environments/*; do terraform -chdir=$i init -backend=false; terraform -chdir=$i validate; done

.plan:
  stage: test
  script:
  - cd environments/${TF_ENV}
  - terraform init
  - terraform plan -lock=false -refresh=false -out=plan.cache
  - gitlab-terraform plan-json -lock=false -refresh=false
  cache:
    key: ${TF_ENV}
    paths:
    - environments/${TF_ENV}/.terraform
  artifacts:
    name: plan
    paths:
    - environments/${TF_ENV}/plan.cache
    reports:
      terraform: environments/${TF_ENV}/plan.json

plan prod:
  extends: .plan
  variables:
    TF_ENV: prod

plan staging:
  extends: .plan
  variables:
    TF_ENV: staging
